name: Continuous integration

on:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'resources/css/**'
      - 'resources/js/**'
      - 'resources/img/**'
      - 'resources/fonts/**'
      - 'resources/views/**'
      - '.github/workflows/build-and-deploy.yml'
    branches:
      - staging
      - master

jobs:
  build-assets-and-deploy:
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build assets
        run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: 'placeholder-because-we-dont-want-errors'

      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy build dir
        run: rsync -avz --delete public/build ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/${{ secrets.DOMAIN }}/public